config/routes.rb
FavoriteLinks::Application.routes.draw do
  root to: 'favorites#index'

  resources :favorites
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :notes, :title, :url

  validates :title, :url, presence: true
  validates_format_of :url, with: URI::regexp(%w(http https)) 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = Favorite.order(:created_at).reverse
  end

  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @favorite }
    end
  end

  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @favorite }
    end
  end

  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: 'Favorite has been created.' }
        format.json { render json: @favorite, status: :created, location: @favorite }
      else
        format.html { render action: 'new', notice: 'Favorite was not created.'}
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @favorite = Favorite.find(params[:id])
  end

    def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Favorite.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to favorites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for @favorite do |f| -%>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url, 'URL' %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>
  <p>
  <%= f.submit %>
  <%= button_to 'Back', root_path %>
  </p> 
<% end -%>

app/views/favorites/edit.html.erb
<h1>Edit Favorite</h1>

<%= render 'form' %>

app/views/favorites/index.html.erb
<h1>Favorite Links</h1>

<table>
  <tr>
    <th>Date Created</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.created_at %></td>
    <td id='title' ><%= link_to favorite.title, favorite.url %></td>
    <td><%= link_to 'Details', favorite %></td>
    <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
    <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h2>New Favorite</h2>
<p class='alert'><%= notice %></p>

<%= render 'form' %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Details</h2>

<p>
  <b>Date Created:</b>
  <%= @favorite.created_at %>
</p>

<p>
  <b>Title:</b>
  <%= @favorite.title %>
</p>

<p>
  <b>URL:</b>
  <%= @favorite.url %>
</p>

<p>
  <b>Notes:</b>
  <%= @favorite.notes %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FavoriteLinks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>